### ISSUE TITLE
[Feature] 2. Insertion

### ISSUE THREAD

**Issue by eun-seong** [eun-seong/Documents#4]
### TODO

- [x] 입력할 파일(input.txt) 불러오기
- [x] `bool insert(int key, int rid)`
    - [x] 삽입할 위치 탐색할 **search 함수**
    - [x] 추가 후 해당 노드의 엔트리 개수 셀 **count 함수**
        - leaf node일 경우 : `[ceil((B-1)/N), B-1]`
        - non-leaf node일 경우 : `[ceil(B/N)-1, B-1]`
    - [x] 엔트리 개수가 over될 경우 진행할 **split 함수**
        - [x] 해당 노드의 value 중 뒤에서 `(B-ceil(B/2))`개의 엔트리 저장
        - [x] count 함수 재귀(아마도...?)

### pseudo code
```c++
stack path = searchInsertPlace(search-key value);

if( (BID의 엔트리 개수 + 1) 이 정상범위) {
    insertEntry(BID, search-key);
    return BID;
}

do {
    newBID = split(BID, newEntry);
    if( parentNode가 없음) newRootNode 생성;
    parentNode에 newBID의 가장 작은 Entry 삽입;
} while( (parentNode 엔트리 개수+1) 정상 );
```

* * *

### 요구 사항
```shell
$ btree.exe i [btree binary file] [records text file]
$ btree.exe i btree.bin insert.txt
```
* command **'i'**
* [records text file]을 읽고, [btree binary file]에 노드(엔트리)를 삽입
* [records text file]의 포맷
    ```
    Key, ID\n
    Key, ID\n
    ...
    ```

**Comment by eun-seong** [comment]
`bool isLeafNodeInRightRange(NumOfEntry)`
`bool isNodeInRightRange(NumOfEntry)`
`int insertEntry(BID, entry)` : BID에 entry추가
`int split(BID, newEntry)` : 새로운 노드 생성 후 값 추가

**Comment by eun-seong** [comment]
* 현재까지 한 방식 : insert 파일을 모두 읽은 후 마지막에 한 번에 파일에 출력

이렇게 해도 되지만 교수님이 원하던 방식은 아니라고 함.
한 줄씩 읽어서 바이너리 파일에 바로 쓰는 것 + 노드가 필요할 경우 `getNode(BID)` 함수를 이용해 바이너리 파일에서 바로 읽어오는 것

코드를 정성적으로 보지는 않기 때문에 어떻게 구현하든 상관없으나 저렇게 하는 게 좋을 듯하다..

그런데 의도가 이해되지 않는다. 파일 입출력을 연습시키려는 건가? 아니면 파일을 메모리라고 생각하고(파일입출력 비효율적인 거 신경X) block에 따른 접근...?
insert할 때마다 파일 읽고 쓰는 거 너무 비효율적이라 생각해서 이렇게 했더니 비효율적인 거 맞다고 해버리시네. 이걸 다 하고 나면 의도를 파악할 수 있겠지.

* * *

### 방식을 바꿀 경우 변경되는 것
* 파일에 저장할 때 비어있는 엔트리의 key와 value는 `INT_MAX`로 구성해야 함(현재는 0)
* `BTree`에서 `nodes` 벡터가 필요없어짐
    * `nodes[BID]`로 접근하는 대신 `getNode(BID)`로 파일 읽기 
* `getNode(BID)`
    * entry를 벡터에 모두 담아야 함
* split
    * 새로운 BID를 가져오는 함수 필요함
        * 파일 마지막에 있는 block의 BID 가져오기 or 
        * `BTree`에 block의 개수 저장하기

**Comment by eun-seong** [comment]
* tree에 저장하는 방식이 아닌 binary file에 바로 저장하는 방식으로 변경
* `BTree`의 멤버 변수 `nodes` 삭제
* `wrtieTreeToFile()` 메소드 삭제

약간의 리팩토링

**Comment by eun-seong** [comment]
![IMG_1B61BA24000E-1](https://user-images.githubusercontent.com/49540564/120892252-4f945c00-c648-11eb-8fa1-bd63971b574d.jpeg)

sample_insertion_input.txt 실행 후 트리 결과
